language: python
cache: pip
sudo: false

python:
  - "3.5"

env:
  - TOX_ENV=py36-django-111
  - TOX_ENV=py35-django-111
  - TOX_ENV=py27-django-111
  - TOX_ENV=py36-django-20
  - TOX_ENV=py35-django-20
  - TOX_ENV=py36-django-master
  - TOX_ENV=py35-django-master

matrix:
  fast_finish: true
  include:
    - python: 3.6
      env: TOX_ENV=py36-django-111
    - python: 3.5
      env: TOX_ENV=py35-django-111
    - python: 2.7
      env: TOX_ENV=py27-django-111
    - python: 3.6
      env: TOX_ENV=py36-django-20
    - python: 3.5
      env: TOX_ENV=py35-django-20
    - python: 3.6
      env: TOX_ENV=py36-django-master
    - python: 3.5
      env: TOX_ENV=py35-django-master

  allow_failures:
    - env: TOX_ENV=py35-django-master
    # - env: TOX_ENV=py36-django-master

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
# install: pip install pytest-django

# command to run tests using coverage, e.g. python setup.py test
script: tox -e $TOX_ENV

install:
  - pip install tox codecov

after_success:
  - codecov -e TOX_ENV
