# Config file for automatic testing at travis-ci.org

language: python

env:
  - TOX_ENV=py27-django17
  - TOX_ENV=py27-django18
  - TOX_ENV=py27-django19
  - TOX_ENV=py34-django17
  - TOX_ENV=py34-django18
  - TOX_ENV=py34-django19

cache: pip
sudo: false

install:
  - pip install tox

script:
  - tox -e $TOX_ENV
